export default {
  fontFamily: [
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'Noto Sans',
    'sans-serif',
    'Apple Color Emoji',
    'Segoe UI Emoji',
    'Segoe UI Symbol',
  ],
  fontSizes: {
    small: '0.8rem',
    medium: '2em',
    large: '3em',
  },
  colors: {
    body: '#e8e8e8',
    primary: '#001228',
    secondary: '#e2e8f0',
    third: '#1a202c',
    fourth: '#0b2239',
    white: '#fff',
    black: '#000f20',
    gray: '#9c9c9c',
    grayLight: '#e8e8e8',
    grayMedium: '#6d7681',
    blue: '#0f5fa3',
  },
};
